"""stock lots and movement lot_id

Revision ID: 17c1e43bc1c3
Revises: d48c011ea797
Create Date: 2026-05-13 15:13:46.345703

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '17c1e43bc1c3'
down_revision: Union[str, Sequence[str], None] = 'd48c011ea797'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stock_lots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('warehouse_id', sa.Integer(), nullable=False),
    sa.Column('lot_number', sa.String(length=60), nullable=False),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=True),
    sa.Column('received_at', sa.DateTime(), nullable=False),
    sa.Column('note', sa.String(length=300), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stock_lots_expiry_date'), 'stock_lots', ['expiry_date'], unique=False)
    op.create_index(op.f('ix_stock_lots_product_id'), 'stock_lots', ['product_id'], unique=False)
    op.create_index(op.f('ix_stock_lots_received_at'), 'stock_lots', ['received_at'], unique=False)
    op.create_index(op.f('ix_stock_lots_warehouse_id'), 'stock_lots', ['warehouse_id'], unique=False)
    op.add_column('stock_movements', sa.Column('lot_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_stock_movements_lot_id'), 'stock_movements', ['lot_id'], unique=False)
    op.create_foreign_key(None, 'stock_movements', 'stock_lots', ['lot_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'stock_movements', type_='foreignkey')
    op.drop_index(op.f('ix_stock_movements_lot_id'), table_name='stock_movements')
    op.drop_column('stock_movements', 'lot_id')
    op.drop_index(op.f('ix_stock_lots_warehouse_id'), table_name='stock_lots')
    op.drop_index(op.f('ix_stock_lots_received_at'), table_name='stock_lots')
    op.drop_index(op.f('ix_stock_lots_product_id'), table_name='stock_lots')
    op.drop_index(op.f('ix_stock_lots_expiry_date'), table_name='stock_lots')
    op.drop_table('stock_lots')
    # ### end Alembic commands ###
