"""marketplace: suppliers/admin extras + purchase orders + nearby shops + recommendations

Revision ID: 2762204367e3
Revises: a4588707d6de
Create Date: 2026-05-13 20:53:14.537069

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2762204367e3'
down_revision: Union[str, Sequence[str], None] = 'a4588707d6de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nearby_shops',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('shop_type', sa.String(length=60), nullable=True),
    sa.Column('city', sa.String(length=80), nullable=False),
    sa.Column('district', sa.String(length=80), nullable=True),
    sa.Column('distance_km', sa.Float(), nullable=True),
    sa.Column('preferred_carrier', sa.String(length=60), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_nearby_shops_city'), 'nearby_shops', ['city'], unique=False)
    op.create_index(op.f('ix_nearby_shops_district'), 'nearby_shops', ['district'], unique=False)
    op.create_index(op.f('ix_nearby_shops_is_active'), 'nearby_shops', ['is_active'], unique=False)
    op.create_index(op.f('ix_nearby_shops_preferred_carrier'), 'nearby_shops', ['preferred_carrier'], unique=False)
    op.create_table('nearby_shop_purchases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shop_id', sa.Integer(), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=True),
    sa.Column('product_name', sa.String(length=120), nullable=False),
    sa.Column('product_category', sa.String(length=60), nullable=True),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('unit_cost', sa.Float(), nullable=False),
    sa.Column('carrier', sa.String(length=60), nullable=True),
    sa.Column('purchased_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['shop_id'], ['nearby_shops.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_nearby_shop_purchases_product_name'), 'nearby_shop_purchases', ['product_name'], unique=False)
    op.create_index(op.f('ix_nearby_shop_purchases_purchased_at'), 'nearby_shop_purchases', ['purchased_at'], unique=False)
    op.create_index(op.f('ix_nearby_shop_purchases_shop_id'), 'nearby_shop_purchases', ['shop_id'], unique=False)
    op.create_index(op.f('ix_nearby_shop_purchases_supplier_id'), 'nearby_shop_purchases', ['supplier_id'], unique=False)
    op.create_table('purchase_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'SENT', 'CONFIRMED', 'RECEIVED', 'CANCELLED', name='purchase_order_status'), nullable=False),
    sa.Column('total_cost', sa.Float(), nullable=False),
    sa.Column('expected_delivery', sa.Date(), nullable=True),
    sa.Column('received_at', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('ai_suggested', sa.Boolean(), nullable=False),
    sa.Column('suggestion_reason', sa.String(length=500), nullable=True),
    sa.Column('created_by_admin_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_admin_id'], ['admin_users.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_purchase_orders_ai_suggested'), 'purchase_orders', ['ai_suggested'], unique=False)
    op.create_index(op.f('ix_purchase_orders_created_at'), 'purchase_orders', ['created_at'], unique=False)
    op.create_index(op.f('ix_purchase_orders_status'), 'purchase_orders', ['status'], unique=False)
    op.create_index(op.f('ix_purchase_orders_supplier_id'), 'purchase_orders', ['supplier_id'], unique=False)
    op.create_table('marketplace_recommendations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('product_name', sa.String(length=120), nullable=False),
    sa.Column('suggested_supplier_id', sa.Integer(), nullable=True),
    sa.Column('suggested_quantity', sa.Float(), nullable=False),
    sa.Column('estimated_unit_cost', sa.Float(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('reasoning', sa.String(length=800), nullable=False),
    sa.Column('nearby_signal_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('applied_purchase_order_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['applied_purchase_order_id'], ['purchase_orders.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['suggested_supplier_id'], ['suppliers.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_marketplace_recommendations_created_at'), 'marketplace_recommendations', ['created_at'], unique=False)
    op.create_index(op.f('ix_marketplace_recommendations_product_id'), 'marketplace_recommendations', ['product_id'], unique=False)
    op.create_index(op.f('ix_marketplace_recommendations_product_name'), 'marketplace_recommendations', ['product_name'], unique=False)
    op.create_index(op.f('ix_marketplace_recommendations_status'), 'marketplace_recommendations', ['status'], unique=False)
    op.create_table('purchase_order_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('purchase_order_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('unit_cost', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['purchase_order_id'], ['purchase_orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_purchase_order_items_product_id'), 'purchase_order_items', ['product_id'], unique=False)
    op.create_index(op.f('ix_purchase_order_items_purchase_order_id'), 'purchase_order_items', ['purchase_order_id'], unique=False)
    op.add_column('admin_users', sa.Column('city', sa.String(length=80), nullable=True))
    op.add_column('admin_users', sa.Column('district', sa.String(length=80), nullable=True))
    op.add_column('admin_users', sa.Column('preferred_carrier', sa.String(length=60), nullable=True))
    op.create_index(op.f('ix_admin_users_city'), 'admin_users', ['city'], unique=False)
    op.add_column('suppliers', sa.Column('category', sa.String(length=60), nullable=True))
    op.add_column('suppliers', sa.Column('carrier', sa.String(length=60), nullable=True))
    op.add_column('suppliers', sa.Column('city', sa.String(length=80), nullable=True))
    op.add_column('suppliers', sa.Column('district', sa.String(length=80), nullable=True))
    op.add_column('suppliers', sa.Column('description', sa.String(length=500), nullable=True))
    op.add_column('suppliers', sa.Column('rating', sa.Float(), nullable=True))
    op.create_index(op.f('ix_suppliers_carrier'), 'suppliers', ['carrier'], unique=False)
    op.create_index(op.f('ix_suppliers_category'), 'suppliers', ['category'], unique=False)
    op.create_index(op.f('ix_suppliers_city'), 'suppliers', ['city'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_suppliers_city'), table_name='suppliers')
    op.drop_index(op.f('ix_suppliers_category'), table_name='suppliers')
    op.drop_index(op.f('ix_suppliers_carrier'), table_name='suppliers')
    op.drop_column('suppliers', 'rating')
    op.drop_column('suppliers', 'description')
    op.drop_column('suppliers', 'district')
    op.drop_column('suppliers', 'city')
    op.drop_column('suppliers', 'carrier')
    op.drop_column('suppliers', 'category')
    op.drop_index(op.f('ix_admin_users_city'), table_name='admin_users')
    op.drop_column('admin_users', 'preferred_carrier')
    op.drop_column('admin_users', 'district')
    op.drop_column('admin_users', 'city')
    op.drop_index(op.f('ix_purchase_order_items_purchase_order_id'), table_name='purchase_order_items')
    op.drop_index(op.f('ix_purchase_order_items_product_id'), table_name='purchase_order_items')
    op.drop_table('purchase_order_items')
    op.drop_index(op.f('ix_marketplace_recommendations_status'), table_name='marketplace_recommendations')
    op.drop_index(op.f('ix_marketplace_recommendations_product_name'), table_name='marketplace_recommendations')
    op.drop_index(op.f('ix_marketplace_recommendations_product_id'), table_name='marketplace_recommendations')
    op.drop_index(op.f('ix_marketplace_recommendations_created_at'), table_name='marketplace_recommendations')
    op.drop_table('marketplace_recommendations')
    op.drop_index(op.f('ix_purchase_orders_supplier_id'), table_name='purchase_orders')
    op.drop_index(op.f('ix_purchase_orders_status'), table_name='purchase_orders')
    op.drop_index(op.f('ix_purchase_orders_created_at'), table_name='purchase_orders')
    op.drop_index(op.f('ix_purchase_orders_ai_suggested'), table_name='purchase_orders')
    op.drop_table('purchase_orders')
    op.drop_index(op.f('ix_nearby_shop_purchases_supplier_id'), table_name='nearby_shop_purchases')
    op.drop_index(op.f('ix_nearby_shop_purchases_shop_id'), table_name='nearby_shop_purchases')
    op.drop_index(op.f('ix_nearby_shop_purchases_purchased_at'), table_name='nearby_shop_purchases')
    op.drop_index(op.f('ix_nearby_shop_purchases_product_name'), table_name='nearby_shop_purchases')
    op.drop_table('nearby_shop_purchases')
    op.drop_index(op.f('ix_nearby_shops_preferred_carrier'), table_name='nearby_shops')
    op.drop_index(op.f('ix_nearby_shops_is_active'), table_name='nearby_shops')
    op.drop_index(op.f('ix_nearby_shops_district'), table_name='nearby_shops')
    op.drop_index(op.f('ix_nearby_shops_city'), table_name='nearby_shops')
    op.drop_table('nearby_shops')
    # ### end Alembic commands ###
