"""lot actions

Revision ID: 28f9ffade239
Revises: b3efcaaaf779
Create Date: 2026-05-13 16:22:00.936446

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '28f9ffade239'
down_revision: Union[str, Sequence[str], None] = 'b3efcaaaf779'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lot_actions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lot_id', sa.Integer(), nullable=False),
    sa.Column('action_type', sa.Enum('DISCOUNT', 'BUNDLE', 'WASTE', 'NOTIFY', 'DELAY_REORDER', name='lot_action_type'), nullable=False),
    sa.Column('subject', sa.String(length=200), nullable=False),
    sa.Column('description', sa.String(length=1500), nullable=False),
    sa.Column('suggested_discount_pct', sa.Float(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPLIED', 'DISMISSED', name='lot_action_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('applied_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['lot_id'], ['stock_lots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lot_actions_created_at'), 'lot_actions', ['created_at'], unique=False)
    op.create_index(op.f('ix_lot_actions_lot_id'), 'lot_actions', ['lot_id'], unique=False)
    op.create_index(op.f('ix_lot_actions_status'), 'lot_actions', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_lot_actions_status'), table_name='lot_actions')
    op.drop_index(op.f('ix_lot_actions_lot_id'), table_name='lot_actions')
    op.drop_index(op.f('ix_lot_actions_created_at'), table_name='lot_actions')
    op.drop_table('lot_actions')
    # ### end Alembic commands ###
