"""admin telegram chat id

Revision ID: 565a5247e68a
Revises: 80f6c8fd81ed
Create Date: 2026-05-13 15:36:08.155279

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '565a5247e68a'
down_revision: Union[str, Sequence[str], None] = '80f6c8fd81ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin_users', sa.Column('telegram_chat_id', sa.BigInteger(), nullable=True))
    op.add_column(
        'admin_users',
        sa.Column(
            'briefing_enabled',
            sa.Boolean(),
            nullable=False,
            server_default=sa.false(),
        ),
    )
    op.create_index(op.f('ix_admin_users_telegram_chat_id'), 'admin_users', ['telegram_chat_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_admin_users_telegram_chat_id'), table_name='admin_users')
    op.drop_column('admin_users', 'briefing_enabled')
    op.drop_column('admin_users', 'telegram_chat_id')
    # ### end Alembic commands ###
