"""product max_stock

Revision ID: 5b13f07acc7c
Revises: 17c1e43bc1c3
Create Date: 2026-05-13 15:19:01.349701

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b13f07acc7c'
down_revision: Union[str, Sequence[str], None] = '17c1e43bc1c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('max_stock', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'max_stock')
    # ### end Alembic commands ###
