"""customer complaints

Revision ID: 80f6c8fd81ed
Revises: 5b13f07acc7c
Create Date: 2026-05-13 15:32:04.611412

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '80f6c8fd81ed'
down_revision: Union[str, Sequence[str], None] = '5b13f07acc7c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer_complaints',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('telegram_user_id', sa.BigInteger(), nullable=True),
    sa.Column('message_text', sa.String(length=2000), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('signals', sa.String(length=300), nullable=True),
    sa.Column('resolved', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customer_complaints_created_at'), 'customer_complaints', ['created_at'], unique=False)
    op.create_index(op.f('ix_customer_complaints_customer_id'), 'customer_complaints', ['customer_id'], unique=False)
    op.create_index(op.f('ix_customer_complaints_resolved'), 'customer_complaints', ['resolved'], unique=False)
    op.create_index(op.f('ix_customer_complaints_risk_score'), 'customer_complaints', ['risk_score'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_customer_complaints_risk_score'), table_name='customer_complaints')
    op.drop_index(op.f('ix_customer_complaints_resolved'), table_name='customer_complaints')
    op.drop_index(op.f('ix_customer_complaints_customer_id'), table_name='customer_complaints')
    op.drop_index(op.f('ix_customer_complaints_created_at'), table_name='customer_complaints')
    op.drop_table('customer_complaints')
    # ### end Alembic commands ###
