"""social media accounts posts assets

Revision ID: a4588707d6de
Revises: 0b94610fb76f
Create Date: 2026-05-13 17:44:06.320557

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a4588707d6de'
down_revision: Union[str, Sequence[str], None] = '0b94610fb76f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('social_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.Enum('INSTAGRAM', 'YOUTUBE', 'TIKTOK', 'FACEBOOK', 'TWITTER', 'THREADS', 'LINKEDIN', name='social_platform'), nullable=False),
    sa.Column('handle', sa.String(length=100), nullable=False),
    sa.Column('display_name', sa.String(length=150), nullable=True),
    sa.Column('profile_url', sa.String(length=300), nullable=True),
    sa.Column('access_token', sa.String(length=1000), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('connected_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('platform', 'handle', name='uq_social_platform_handle')
    )
    op.create_index(op.f('ix_social_accounts_is_active'), 'social_accounts', ['is_active'], unique=False)
    op.create_index(op.f('ix_social_accounts_platform'), 'social_accounts', ['platform'], unique=False)
    op.create_table('social_posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('content', sa.String(length=3000), nullable=False),
    sa.Column('target_platforms', sa.String(length=200), nullable=False),
    sa.Column('hashtags', sa.String(length=500), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'SCHEDULED', 'PUBLISHING', 'PUBLISHED', 'FAILED', name='social_post_status'), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('ai_generated', sa.Boolean(), nullable=False),
    sa.Column('prompt', sa.String(length=500), nullable=True),
    sa.Column('related_product_id', sa.Integer(), nullable=True),
    sa.Column('last_error', sa.String(length=500), nullable=True),
    sa.Column('created_by_admin_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_admin_id'], ['admin_users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['related_product_id'], ['products.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_social_posts_created_at'), 'social_posts', ['created_at'], unique=False)
    op.create_index(op.f('ix_social_posts_related_product_id'), 'social_posts', ['related_product_id'], unique=False)
    op.create_index(op.f('ix_social_posts_scheduled_at'), 'social_posts', ['scheduled_at'], unique=False)
    op.create_index(op.f('ix_social_posts_status'), 'social_posts', ['status'], unique=False)
    op.create_table('social_assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('asset_type', sa.Enum('IMAGE', 'VIDEO', name='social_asset_type'), nullable=False),
    sa.Column('prompt', sa.String(length=1000), nullable=True),
    sa.Column('provider', sa.String(length=40), nullable=True),
    sa.Column('url', sa.String(length=500), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'GENERATING', 'READY', 'FAILED', name='social_asset_status'), nullable=False),
    sa.Column('error', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['social_posts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_social_assets_post_id'), 'social_assets', ['post_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_social_assets_post_id'), table_name='social_assets')
    op.drop_table('social_assets')
    op.drop_index(op.f('ix_social_posts_status'), table_name='social_posts')
    op.drop_index(op.f('ix_social_posts_scheduled_at'), table_name='social_posts')
    op.drop_index(op.f('ix_social_posts_related_product_id'), table_name='social_posts')
    op.drop_index(op.f('ix_social_posts_created_at'), table_name='social_posts')
    op.drop_table('social_posts')
    op.drop_index(op.f('ix_social_accounts_platform'), table_name='social_accounts')
    op.drop_index(op.f('ix_social_accounts_is_active'), table_name='social_accounts')
    op.drop_table('social_accounts')
    # ### end Alembic commands ###
