"""complaint subject description source

Revision ID: b3efcaaaf779
Revises: 565a5247e68a
Create Date: 2026-05-13 15:50:56.757390

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b3efcaaaf779'
down_revision: Union[str, Sequence[str], None] = '565a5247e68a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'customer_complaints',
        sa.Column('subject', sa.String(length=200), nullable=False, server_default='Şikayet sinyali'),
    )
    op.add_column('customer_complaints', sa.Column('description', sa.String(length=2000), nullable=True))
    op.add_column(
        'customer_complaints',
        sa.Column('source', sa.String(length=40), nullable=False, server_default='telegram_message'),
    )
    op.add_column('customer_complaints', sa.Column('related_entity_type', sa.String(length=40), nullable=True))
    op.add_column('customer_complaints', sa.Column('related_entity_id', sa.Integer(), nullable=True))
    op.add_column(
        'customer_complaints',
        sa.Column('auto_generated', sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    # Mevcut satirlar icin subject = message_text'in ilk 80 karakteri
    op.execute(
        """
        UPDATE customer_complaints
        SET subject = COALESCE(LEFT(message_text, 80), 'Şikayet sinyali')
        WHERE subject = 'Şikayet sinyali'
        """
    )
    op.alter_column('customer_complaints', 'message_text',
               existing_type=sa.VARCHAR(length=2000),
               nullable=True)
    op.create_index(op.f('ix_customer_complaints_auto_generated'), 'customer_complaints', ['auto_generated'], unique=False)
    op.create_index(op.f('ix_customer_complaints_source'), 'customer_complaints', ['source'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_customer_complaints_source'), table_name='customer_complaints')
    op.drop_index(op.f('ix_customer_complaints_auto_generated'), table_name='customer_complaints')
    op.alter_column('customer_complaints', 'message_text',
               existing_type=sa.VARCHAR(length=2000),
               nullable=False)
    op.drop_column('customer_complaints', 'auto_generated')
    op.drop_column('customer_complaints', 'related_entity_id')
    op.drop_column('customer_complaints', 'related_entity_type')
    op.drop_column('customer_complaints', 'source')
    op.drop_column('customer_complaints', 'description')
    op.drop_column('customer_complaints', 'subject')
    # ### end Alembic commands ###
