"""warehouses and stock balances

Revision ID: d48c011ea797
Revises: c71dcc346bda
Create Date: 2026-05-13 15:04:21.905754

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd48c011ea797'
down_revision: Union[str, Sequence[str], None] = 'c71dcc346bda'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('warehouses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=True),
    sa.Column('address', sa.String(length=300), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_warehouses_is_active'), 'warehouses', ['is_active'], unique=False)
    op.create_table('stock_balances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('warehouse_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id', 'warehouse_id', name='uq_stock_balance')
    )
    op.create_index(op.f('ix_stock_balances_product_id'), 'stock_balances', ['product_id'], unique=False)
    op.create_index(op.f('ix_stock_balances_warehouse_id'), 'stock_balances', ['warehouse_id'], unique=False)
    op.add_column('stock_movements', sa.Column('warehouse_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_stock_movements_warehouse_id'), 'stock_movements', ['warehouse_id'], unique=False)
    op.create_foreign_key(None, 'stock_movements', 'warehouses', ['warehouse_id'], ['id'], ondelete='SET NULL')

    # Backfill: default warehouse, balances from products.stock, all movements -> default
    op.execute(
        """
        INSERT INTO warehouses (name, code, is_default, is_active, created_at)
        VALUES ('Ana Depo', 'main', TRUE, TRUE, NOW())
        """
    )
    op.execute(
        """
        INSERT INTO stock_balances (product_id, warehouse_id, quantity, updated_at)
        SELECT p.id, w.id, p.stock, NOW()
        FROM products p, warehouses w
        WHERE w.is_default = TRUE
        """
    )
    op.execute(
        """
        UPDATE stock_movements
        SET warehouse_id = (SELECT id FROM warehouses WHERE is_default = TRUE)
        WHERE warehouse_id IS NULL
        """
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'stock_movements', type_='foreignkey')
    op.drop_index(op.f('ix_stock_movements_warehouse_id'), table_name='stock_movements')
    op.drop_column('stock_movements', 'warehouse_id')
    op.drop_index(op.f('ix_stock_balances_warehouse_id'), table_name='stock_balances')
    op.drop_index(op.f('ix_stock_balances_product_id'), table_name='stock_balances')
    op.drop_table('stock_balances')
    op.drop_index(op.f('ix_warehouses_is_active'), table_name='warehouses')
    op.drop_table('warehouses')
    # ### end Alembic commands ###
